2019-12-20T09:14:17.838295+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/whitenoise/django.py", line 1, in <module>
2019-12-20T09:14:17.838296+00:00 app[web.1]: raise ImportError(
2019-12-20T09:14:17.838298+00:00 app[web.1]: ImportError:
2019-12-20T09:14:17.838299+00:00 app[web.1]: 
2019-12-20T09:14:17.838301+00:00 app[web.1]: Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
2019-12-20T09:14:17.838302+00:00 app[web.1]: This can be fixed by following the upgrade instructions at:
2019-12-20T09:14:17.838303+00:00 app[web.1]: http://whitenoise.evans.io/en/stable/changelog.html#v4-0
2019-12-20T09:14:17.838305+00:00 app[web.1]: 
2019-12-20T09:14:17.838306+00:00 app[web.1]: 
2019-12-20T09:14:17.838316+00:00 app[web.1]: [2019-12-20 09:14:17 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-12-20T09:14:17.945285+00:00 app[web.1]: [2019-12-20 09:14:17 +0000] [4] [INFO] Shutting down: Master
2019-12-20T09:14:17.945364+00:00 app[web.1]: [2019-12-20 09:14:17 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-12-20T09:15:14.112555+00:00 heroku[web.1]: State changed from crashed to starting
2019-12-20T09:15:12.647762+00:00 app[api]: Deploy 822c6ec2 by user campos.talita@ymail.com
2019-12-20T09:15:12.647762+00:00 app[api]: Release v21 created by user campos.talita@ymail.com
2019-12-20T09:15:19.699425+00:00 heroku[web.1]: Starting process with command `gunicorn ecommerce.wsgi`
2019-12-20T09:15:21.937557+00:00 heroku[web.1]: State changed from starting to crashed
2019-12-20T09:15:21.921067+00:00 heroku[web.1]: Process exited with status 3
2019-12-20T09:15:21.840476+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [4] [INFO] Shutting down: Master
2019-12-20T09:15:21.840685+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-12-20T09:15:21.495760+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [4] [INFO] Starting gunicorn 20.0.4
2019-12-20T09:15:21.496418+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [4] [INFO] Listening at: http://0.0.0.0:10958 (4)
2019-12-20T09:15:21.496508+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [4] [INFO] Using worker: sync
2019-12-20T09:15:21.499889+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [9] [INFO] Booting worker with pid: 9
2019-12-20T09:15:21.529113+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [10] [INFO] Booting worker with pid: 10
2019-12-20T09:15:21.693774+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [9] [ERROR] Exception in worker process
2019-12-20T09:15:21.693777+00:00 app[web.1]: Traceback (most recent call last):
2019-12-20T09:15:21.693779+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-12-20T09:15:21.693780+00:00 app[web.1]: worker.init_process()
2019-12-20T09:15:21.693782+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2019-12-20T09:15:21.693783+00:00 app[web.1]: self.load_wsgi()
2019-12-20T09:15:21.693785+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2019-12-20T09:15:21.693786+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-12-20T09:15:21.693787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-12-20T09:15:21.693788+00:00 app[web.1]: self.callable = self.load()
2019-12-20T09:15:21.693790+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2019-12-20T09:15:21.693791+00:00 app[web.1]: return self.load_wsgiapp()
2019-12-20T09:15:21.693792+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2019-12-20T09:15:21.693794+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-12-20T09:15:21.693795+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2019-12-20T09:15:21.693796+00:00 app[web.1]: mod = importlib.import_module(module)
2019-12-20T09:15:21.693797+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2019-12-20T09:15:21.693799+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2019-12-20T09:15:21.693800+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2019-12-20T09:15:21.693801+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2019-12-20T09:15:21.693803+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2019-12-20T09:15:21.693804+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2019-12-20T09:15:21.693805+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2019-12-20T09:15:21.693806+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-12-20T09:15:21.693808+00:00 app[web.1]: File "/app/ecommerce/wsgi.py", line 13, in <module>
2019-12-20T09:15:21.693810+00:00 app[web.1]: from whitenoise.django import DjangoWhiteNoise
2019-12-20T09:15:21.693811+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/whitenoise/django.py", line 1, in <module>
2019-12-20T09:15:21.693812+00:00 app[web.1]: raise ImportError(
2019-12-20T09:15:21.693814+00:00 app[web.1]: ImportError:
2019-12-20T09:15:21.693815+00:00 app[web.1]: 
2019-12-20T09:15:21.693816+00:00 app[web.1]: Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
2019-12-20T09:15:21.693818+00:00 app[web.1]: This can be fixed by following the upgrade instructions at:
2019-12-20T09:15:21.693819+00:00 app[web.1]: http://whitenoise.evans.io/en/stable/changelog.html#v4-0
2019-12-20T09:15:21.693820+00:00 app[web.1]: 
2019-12-20T09:15:21.693822+00:00 app[web.1]: 
2019-12-20T09:15:21.693943+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [9] [INFO] Worker exiting (pid: 9)
2019-12-20T09:15:21.732027+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [10] [ERROR] Exception in worker process
2019-12-20T09:15:21.732030+00:00 app[web.1]: Traceback (most recent call last):
2019-12-20T09:15:21.732032+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-12-20T09:15:21.732033+00:00 app[web.1]: worker.init_process()
2019-12-20T09:15:21.732035+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2019-12-20T09:15:21.732036+00:00 app[web.1]: self.load_wsgi()
2019-12-20T09:15:21.732037+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2019-12-20T09:15:21.732039+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-12-20T09:15:21.732040+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-12-20T09:15:21.732041+00:00 app[web.1]: self.callable = self.load()
2019-12-20T09:15:21.732043+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2019-12-20T09:15:21.732044+00:00 app[web.1]: return self.load_wsgiapp()
2019-12-20T09:15:21.732046+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2019-12-20T09:15:21.732047+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-12-20T09:15:21.732048+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2019-12-20T09:15:21.732050+00:00 app[web.1]: mod = importlib.import_module(module)
2019-12-20T09:15:21.732051+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2019-12-20T09:15:21.732052+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2019-12-20T09:15:21.732054+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2019-12-20T09:15:21.732055+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2019-12-20T09:15:21.732056+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2019-12-20T09:15:21.732058+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2019-12-20T09:15:21.732059+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2019-12-20T09:15:21.732061+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-12-20T09:15:21.732062+00:00 app[web.1]: File "/app/ecommerce/wsgi.py", line 13, in <module>
2019-12-20T09:15:21.732064+00:00 app[web.1]: from whitenoise.django import DjangoWhiteNoise
2019-12-20T09:15:21.732065+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/whitenoise/django.py", line 1, in <module>
2019-12-20T09:15:21.732067+00:00 app[web.1]: raise ImportError(
2019-12-20T09:15:21.732068+00:00 app[web.1]: ImportError:
2019-12-20T09:15:21.732069+00:00 app[web.1]: 
2019-12-20T09:15:21.732071+00:00 app[web.1]: Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
2019-12-20T09:15:21.732072+00:00 app[web.1]: This can be fixed by following the upgrade instructions at:
2019-12-20T09:15:21.732073+00:00 app[web.1]: http://whitenoise.evans.io/en/stable/changelog.html#v4-0
2019-12-20T09:15:21.732075+00:00 app[web.1]: 
2019-12-20T09:15:21.732076+00:00 app[web.1]: 
2019-12-20T09:15:21.732275+00:00 app[web.1]: [2019-12-20 09:15:21 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-12-20T09:15:23.000000+00:00 app[api]: Build succeeded
2019-12-20T09:16:08.795136+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=oldcurrencyapp.herokuapp.com request_id=0bb874c5-e890-415a-9dd8-11424915c547 fwd="80.233.42.131" dyno= connect= service= status=503 bytes= protocol=https
2019-12-20T09:16:09.486796+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=oldcurrencyapp.herokuapp.com request_id=45046b34-0b41-4582-95dd-a0edb6cc295d fwd="80.233.42.131" dyno= connect= service= status=503 bytes= protocol=https
Terminate batch job (Y/N)? 
